//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int HotelId { get; set; }
        public string DisplayName { get; set; }
        public string DisplayNameAr { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string State { get; set; }
        public string CityName { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public Nullable<byte> StarRating { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public Nullable<short> RoomCount { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string PropertyCategory { get; set; }
        public string ChainCode { get; set; }
        public string AddressAr { get; set; }
    }
}
